var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                    o           ",
   "                                                                 xxxxxxx        ",
   "                                                                                ",
   "                                                 xxxx         xx                ",
   "             yyy                    o o      xx        xxxxx        x           ",
   "  x         yyyyy      o                  xx                       xxx       x  ",
   "  x       yyyyyyyyy                xxxxx                          xxxxx      x  ",
   "  x                                                              xxxxxxx     x  ",
   "  x                                                             xxxxxxxxx    x  ",
   "  x          xxxxxxxx     xxxxxxxxxx                   o o      xxxxxxxxx    x  ",
   "  x        xxx                           xxxxx        xxxxx     xx     xx    x  ",
   "  x   @      x                                                o xx     xx  s x  ",
   "  xxxxxxxxxxxxxxxxxx!!!!!!!xxxx   xxxxxx!!!!!!!xxxxxxx     xxxxxxx     xxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
   ["xxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!v!!!!!v!!!!!!!v!!!!!!v!!!!!!v!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x                                                                                         xxxxxxxxxxxxxxxxx",
    "x                                                                                            xxxxxxxxxxxxxx",
    "x                                                                                              xxxxxxxxxxxx",
    "x                                                                                                xxxxxxxxxx",
    "x                                                                                                       xxx",
    "x                                                                                                 ooooooxxx",
    "x                                                                                                 ooooooxxx",
    "x                              o      o      o       o      o      o                              ooooooxxx",
    "x        o          xxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "x      xxxxx                                                                                            xxx",
    "x                                                                                                       xxx",
    "x                                    o       o        o                                                 xxx",
    "xx                               xxxxxxxxxxxxxxxxxxxxxxxxxxx                                            xxx",
    "xxx                                                         xx                                          xxx",
    "xxxx                                                                                                    xxx",
    "xxxxx                                                            xxxxxxxxx!!!!!xxxxx                    xxx",
    "!!!!!!!!xxxx!!!!xxxxxxxxx  s                                    xxxxxxxxxxxxxxxxxxxxxx                  xxx",
    "xxxxxxxvxxxxvxxvxxxxxxxxxxxxxxxxxxxxxxxx        o    =         xxxxxxxxxxxxxxxxxxxxxxxxx                xxx",
    "x                  xxxxxxxxxxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxx",
    "x                                                                                              x        xxx",
    "x                                                                                              xxxx  o  xxx",
    "x                                                                                                       xxx",
    "x                                                                                                       xxx",
    "x                                                                                                       xxx",
    "x                                                                                                       xxx",
    "x        o                                                     xxxxxxx                                  xxx",
    "x  @   xxxxxxxxxxxxx    =    o          =        o    =     xxxxxxxxxxxxx             =        s        xxx",
    "xxxxxxxxxxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["                                                                                                                               ",
   "                                                                                                                               ",
   "                                                                                                                               ",
   "                                                                                                                               ",
   "                                                                                                                               ",
   "                                                                                                                       xxxxxxxx",
   "                                                                                                                       xxxxxxxx",
   "                                                                                                                       xxxxxxxx",
   "                                                                                 xx                                    xxxxxxxx",
   "                                                                                xxxx                                   xxxxxxxx",
   "                                                                              xxxxxxx                                  xxxxxxxx",
   "                                                                            xxxxxxxxxxx                                xxxxxxxx",
   "                                                                             xxxxxxxxx                                 xxxxxxxx",
   "                                                                             xxxxxxxxx                                 xxxxxxxx",
   "                                                                             xxxxxxxxx                                 xxxxxxxx",
   "                                                                         xxxxxxxxxxxxxxxxx                             xxxxxxxx",
   "                                                                         xxxxxxxxxxxxxx                                xxxxxxxx",
   "                                                                     xxxxxxxxxxxxxx                                    xxxxxxxx",
   "                                                              xx     xxxxxxxx             xxxx            xx           xxxxxxxx",
   "                                                             xxxx    xxxxxxxx    o    xxxxxxxx           xxxx          xxxxxxxx",
   "                                                            xxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxx         xxxxxxxx",
   "                                                              xx     xxxxxxxxxxxxxxxxxxxxxxxxx xxx        xx           ooooooxx",
   "                                                              xx                                          xx           ooooooxx",
   "                                                              xx !!!!! o !!!! o !!!!!                     xx           ooooooxx",
   "                                                              xx                                          xxxxxxxxxxxxxxxxxxxxx",
   "                                                              xx                               xxxxx         xxxxxxxxxxxxxxxxxx",
   "                                                              xxwwwwwwwwwwwwwwwwwwwwwwww                          xxxxxxxxxxxxx",
   "                                    xxx            xxx        xx      xxxxxxxxxxxxxxxxxxxxxxxxxxxx      xx      o xxxxxxxxxxxxx",
   "                                  xxx       o        xxx                                                      xxxxxxxxxxxxxxxxx",
   "          @  s                 xxxx                   xxxx                   o                              xxxxxxxxxxxxxxxxxxx",
   "          xxxx            xxxxxx!!!!!!!!         !!!!!!!!xxxxxxxx     xxxxxxxxxxxxxxxxx                   xxxxxxxxxxxxxxxxxxxxx",
   "          xxxx!!!!!!!!!!!!xxxxxx!!!!!!!!    o    !!!!!!!!xxxxxxx       xxxxxxxxxxxxxxxx                xxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!xxxx!!!!!!!!!!!!xxxxxx!!!!!!!!         !!!!!!!!xxxxxxx       xxxxxxxxxxxxxxxx                xxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxxx!!!!!!!           !!!!!!!xxxxxxx       xxxxxxxxxxxxxxxx           xx   xxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxxx!!!!!!             !!!!!!xxxxxxx    xxxxxxxxxxxxxxxxxxx       o        xxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!xxxxxx!!!!!!!!!!xxxxxx!!!!!               !!!!!xxxxxxx       xxxxxxxxxxxxxxxx   xxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!        o        !!!!xxxxxxxxx     xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxx",
   "xx        xxxxxx          xxxxxx                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx   o    xxxxx            xxxxx                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx  ooo           xxxxx                           e                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xx               xxxxxxx                                    =          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "       x        x        xxxx       xx        xx       xx               xx      xxxxxxxxxxxxxx    xx        xx     ",
   "        x      x        x    x      xx        xx       xx               xx            xx          xxx       xx     ",
   "         x    x       xx      xx    xx        xx       xx               xx            xx          xx x      xx     ",
   "          x  x        xx      xx    xx        xx       xx               xx            xx          xx  x     xx     ",
   "           xx         xx      xx    xx        xx       xx       x       xx            xx          xx   x    xx     ",
   "           xx         xx      xx    xx        xx        xx     x x     xx             xx          xx    x   xx     ",
   "           xx         xx      xx    xx        xx         xx   x   x   xx              xx          xx     x  xx     ",
   "           xx           x    x        x      x            xx x     x xx               xx          xx      x xx     ",
   "           xx            xxxx          xxxxxx              xx       xx          xxxxxxxxxxxxxx    xx       xxx     ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "                                                                                                                   ",
   "         @                                                                                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]


];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
